@startuml


class Masters_Proj.DecodeFrame
class Masters_Proj.DirectoryCustomFilter
class Masters_Proj.EncodeFrame
class Masters_Proj.ExtendedVCS
class Masters_Proj.ImageCustomFilter
class Masters_Proj.MainFrame
class Masters_Proj.Pixel
@enduml